package com.pojo.parameters.processor;

import com.pojo.parameters.Parameters;

import javax.lang.model.SourceVersion;
import javax.lang.model.element.AnnotationMirror;
import javax.lang.model.element.AnnotationValue;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;
import javax.lang.model.type.ArrayType;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.Elements;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;

/**
 * Collects annotation-declared properties and instance fields into one list.
 */
final class AssembledProperties {

    private static final List<String> INTEGRAL_PRIMITIVES =
            Arrays.asList("byte", "short", "int", "long", "char");

    private final List<AssembledProperty> properties;

    AssembledProperties(List<AssembledProperty> properties) {
        this.properties = Collections.unmodifiableList(new ArrayList<AssembledProperty>(properties));
    }

    List<AssembledProperty> properties() {
        return properties;
    }

    boolean isEmpty() {
        return properties.isEmpty();
    }

    static AssembledProperties from(
            TypeElement type,
            Parameters annotation,
            AnnotationMirror mirror,
            Elements elements,
            BiConsumer<Element, String> error) {
        Map<String, AssembledProperty> byName = new LinkedHashMap<String, AssembledProperty>();

        if (!mergeExistingFields(type, byName, error)) {
            return null;
        }
        if (!addNamedProperties(type, annotation.String(), "String", false, byName, error)) {
            return null;
        }
        if (!addNamedProperties(type, annotation.Boolean(), "Boolean", false, byName, error)) {
            return null;
        }
        if (!addNamedProperties(type, annotation.Byte(), "Byte", false, byName, error)) {
            return null;
        }
        if (!addNamedProperties(type, annotation.Short(), "Short", false, byName, error)) {
            return null;
        }
        if (!addNamedProperties(type, annotation.Integer(), "Integer", false, byName, error)) {
            return null;
        }
        if (!addNamedProperties(type, annotation.Long(), "Long", false, byName, error)) {
            return null;
        }
        if (!addNamedProperties(type, annotation.Character(), "Character", false, byName, error)) {
            return null;
        }
        if (!addNamedProperties(type, annotation.Float(), "Float", false, byName, error)) {
            return null;
        }
        if (!addNamedProperties(type, annotation.Double(), "Double", false, byName, error)) {
            return null;
        }
        if (!addNamedProperties(type, annotation.boolean_(), "boolean", true, byName, error)) {
            return null;
        }
        if (!addNamedProperties(type, annotation.byte_(), "byte", false, byName, error)) {
            return null;
        }
        if (!addNamedProperties(type, annotation.short_(), "short", false, byName, error)) {
            return null;
        }
        if (!addNamedProperties(type, annotation.int_(), "int", false, byName, error)) {
            return null;
        }
        if (!addNamedProperties(type, annotation.long_(), "long", false, byName, error)) {
            return null;
        }
        if (!addNamedProperties(type, annotation.char_(), "char", false, byName, error)) {
            return null;
        }
        if (!addNamedProperties(type, annotation.float_(), "float", false, byName, error)) {
            return null;
        }
        if (!addNamedProperties(type, annotation.double_(), "double", false, byName, error)) {
            return null;
        }
        if (!addOfProperties(type, mirror, elements, byName, error)) {
            return null;
        }
        if (byName.isEmpty()) {
            error.accept(type, "@Parameters must declare at least one property or instance field to merge.");
            return null;
        }
        return new AssembledProperties(new ArrayList<AssembledProperty>(byName.values()));
    }

    String renderJava(String packageName, String className) {
        StringBuilder java = new StringBuilder();
        if (!packageName.isEmpty()) {
            java.append("package ").append(packageName).append(";\n\n");
        }
        if (hasArrayProperty()) {
            java.append("import java.util.Arrays;\n");
        }
        java.append("import java.util.Objects;\n\n");
        java.append("/**\n");
        java.append(" * Generated by {@code @Parameters}. Do not edit.\n");
        java.append(" */\n");
        java.append("public abstract class ").append(className).append(" {\n\n");
        for (AssembledProperty property : properties) {
            java.append("    private ").append(property.typeSource()).append(' ').append(property.name());
            if (property.initializer() != null) {
                java.append(" = ").append(property.initializer());
            }
            java.append(";\n");
        }
        java.append('\n');
        java.append("    protected ").append(className).append("() {\n");
        java.append("    }\n");
        for (AssembledProperty property : properties) {
            appendAccessors(java, property);
        }
        appendEqualsHashCodeToString(java, className);
        java.append("}\n");
        return java.toString();
    }

    private boolean hasArrayProperty() {
        for (AssembledProperty property : properties) {
            if (property.array()) {
                return true;
            }
        }
        return false;
    }

    private static boolean mergeExistingFields(
            TypeElement type,
            Map<String, AssembledProperty> byName,
            BiConsumer<Element, String> error) {
        for (Element enclosed : type.getEnclosedElements()) {
            if (enclosed.getKind() != ElementKind.FIELD || !(enclosed instanceof VariableElement)) {
                continue;
            }
            VariableElement field = (VariableElement) enclosed;
            if (field.getModifiers().contains(Modifier.STATIC)) {
                continue;
            }
            String name = field.getSimpleName().toString();
            if (!SourceVersion.isIdentifier(name) || SourceVersion.isKeyword(name)) {
                error.accept(field, "Cannot merge field into @Parameters: invalid name " + name);
                return false;
            }
            AssembledProperty property = AssembledProperty.fromType(name, field.asType(), null);
            if (!putMerged(type, byName, property, error)) {
                return false;
            }
        }
        return true;
    }

    private static boolean addOfProperties(
            TypeElement type,
            AnnotationMirror mirror,
            Elements elements,
            Map<String, AssembledProperty> byName,
            BiConsumer<Element, String> error) {
        if (mirror == null) {
            return true;
        }
        for (AnnotationMirror nested : nestedAnnotations(mirror, elements, "of")) {
            TypeMirror propertyType = classValue(nested, elements, "Class");
            if (propertyType == null) {
                error.accept(type, "Each @Of must declare Class.");
                return false;
            }
            List<String> names = stringValues(nested, elements, "names");
            if (names.isEmpty()) {
                String derived = decapitalize(simpleName(propertyType));
                if (!SourceVersion.isIdentifier(derived) || SourceVersion.isKeyword(derived)) {
                    error.accept(type, "Type " + propertyType
                            + " produces invalid field name '" + derived
                            + "'; declare names explicitly on @Of.");
                    return false;
                }
                names = Collections.singletonList(derived);
            }
            for (String name : names) {
                if (!SourceVersion.isIdentifier(name) || SourceVersion.isKeyword(name)) {
                    error.accept(type, "Invalid @Of property name: " + name);
                    return false;
                }
                AssembledProperty property = AssembledProperty.fromType(name, propertyType, null);
                if (!putMerged(type, byName, property, error)) {
                    return false;
                }
            }
        }
        return true;
    }

    private static boolean addNamedProperties(
            TypeElement type,
            String[] names,
            String typeSource,
            boolean primitiveBoolean,
            Map<String, AssembledProperty> byName,
            BiConsumer<Element, String> error) {
        for (int i = 0; i < names.length; i++) {
            String name = names[i];
            if (!SourceVersion.isIdentifier(name) || SourceVersion.isKeyword(name)) {
                error.accept(type, "Invalid " + typeSource + " property name: " + name);
                return false;
            }
            AssembledProperty property = new AssembledProperty(name, typeSource, null, primitiveBoolean, false);
            if (!putMerged(type, byName, property, error)) {
                return false;
            }
        }
        return true;
    }

    private static boolean putMerged(
            TypeElement type,
            Map<String, AssembledProperty> byName,
            AssembledProperty property,
            BiConsumer<Element, String> error) {
        AssembledProperty existing = byName.get(property.name());
        if (existing == null) {
            byName.put(property.name(), property);
            return true;
        }
        if (existing.typeSource().equals(property.typeSource())) {
            if (existing.initializer() == null && property.initializer() != null) {
                byName.put(property.name(), property);
            }
            return true;
        }
        error.accept(type, "Duplicate property name with conflicting types: " + property.name()
                + " (" + existing.typeSource() + " vs " + property.typeSource() + ")");
        return false;
    }

    private static void appendAccessors(StringBuilder java, AssembledProperty property) {
        java.append('\n');
        java.append("    public ").append(property.typeSource()).append(' ')
                .append(property.getter()).append("() {\n");
        java.append("        return this.").append(property.name()).append(";\n");
        java.append("    }\n\n");
        java.append("    public void ").append(property.setter()).append('(')
                .append(property.typeSource()).append(' ').append(property.name()).append(") {\n");
        java.append("        this.").append(property.name()).append(" = ").append(property.name()).append(";\n");
        java.append("    }\n");
    }

    private void appendEqualsHashCodeToString(StringBuilder java, String className) {
        java.append('\n');
        java.append("    @Override\n");
        java.append("    public boolean equals(Object o) {\n");
        java.append("        if (this == o) {\n");
        java.append("            return true;\n");
        java.append("        }\n");
        java.append("        if (!(o instanceof ").append(className).append(")) {\n");
        java.append("            return false;\n");
        java.append("        }\n");
        java.append("        ").append(className).append(" that = (").append(className).append(") o;\n");
        if (properties.isEmpty()) {
            java.append("        return true;\n");
        } else {
            java.append("        return ").append(equalsExpression()).append(";\n");
        }
        java.append("    }\n\n");
        java.append("    @Override\n");
        java.append("    public int hashCode() {\n");
        java.append("        return ").append(hashExpression()).append(";\n");
        java.append("    }\n\n");
        java.append("    @Override\n");
        java.append("    public String toString() {\n");
        java.append("        return \"").append(className).append("{\"\n");
        for (int i = 0; i < properties.size(); i++) {
            AssembledProperty property = properties.get(i);
            java.append("                + \"");
            if (i > 0) {
                java.append(", ");
            }
            java.append(property.name()).append("=\" + ");
            java.append(toStringFragment(property)).append('\n');
        }
        java.append("                + '}';\n");
        java.append("    }\n");
    }

    private String equalsExpression() {
        List<String> parts = new ArrayList<String>();
        for (AssembledProperty property : properties) {
            String name = property.name();
            if (property.array()) {
                parts.add("Arrays.equals(this." + name + ", that." + name + ")");
            } else if ("float".equals(property.typeSource())) {
                parts.add("Float.compare(this." + name + ", that." + name + ") == 0");
            } else if ("double".equals(property.typeSource())) {
                parts.add("Double.compare(this." + name + ", that." + name + ") == 0");
            } else if (property.primitiveBoolean() || INTEGRAL_PRIMITIVES.contains(property.typeSource())) {
                parts.add("this." + name + " == that." + name);
            } else {
                parts.add("Objects.equals(this." + name + ", that." + name + ")");
            }
        }
        StringBuilder joined = new StringBuilder();
        for (int i = 0; i < parts.size(); i++) {
            if (i > 0) {
                joined.append("\n                && ");
            }
            joined.append(parts.get(i));
        }
        return joined.toString();
    }

    private String hashExpression() {
        if (properties.isEmpty()) {
            return "0";
        }
        boolean anyArray = hasArrayProperty();
        if (!anyArray) {
            StringBuilder args = new StringBuilder();
            for (int i = 0; i < properties.size(); i++) {
                if (i > 0) {
                    args.append(", ");
                }
                args.append("this.").append(properties.get(i).name());
            }
            return "Objects.hash(" + args + ")";
        }
        StringBuilder expr = new StringBuilder("1");
        for (AssembledProperty property : properties) {
            expr.append(" * 31 + ");
            if (property.array()) {
                expr.append("Arrays.hashCode(this.").append(property.name()).append(')');
            } else {
                expr.append("Objects.hashCode(this.").append(property.name()).append(')');
            }
        }
        return expr.toString();
    }

    private static String toStringFragment(AssembledProperty property) {
        if (property.array()) {
            return "Arrays.toString(this." + property.name() + ")";
        }
        return "this." + property.name();
    }

    static String decapitalize(String name) {
        if (name == null || name.isEmpty()) {
            return name;
        }
        if (name.length() > 1 && Character.isUpperCase(name.charAt(0)) && Character.isUpperCase(name.charAt(1))) {
            return name;
        }
        return Character.toLowerCase(name.charAt(0)) + name.substring(1);
    }

    static String simpleName(TypeMirror type) {
        String rendered = type.toString();
        int array = rendered.indexOf('[');
        String core = array < 0 ? rendered : rendered.substring(0, array);
        int lastDot = core.lastIndexOf('.');
        return lastDot < 0 ? core : core.substring(lastDot + 1);
    }

    static List<AnnotationMirror> nestedAnnotations(AnnotationMirror mirror, Elements elements, String member) {
        Object value = annotationValue(mirror, elements, member);
        if (!(value instanceof List<?>)) {
            return Collections.emptyList();
        }
        List<?> list = (List<?>) value;
        List<AnnotationMirror> nested = new ArrayList<AnnotationMirror>();
        for (Object item : list) {
            Object raw = item instanceof AnnotationValue ? ((AnnotationValue) item).getValue() : item;
            if (raw instanceof AnnotationMirror) {
                nested.add((AnnotationMirror) raw);
            }
        }
        return nested;
    }

    static TypeMirror classValue(AnnotationMirror mirror, Elements elements, String member) {
        Object value = annotationValue(mirror, elements, member);
        return value instanceof TypeMirror ? (TypeMirror) value : null;
    }

    static List<String> stringValues(AnnotationMirror mirror, Elements elements, String member) {
        Object value = annotationValue(mirror, elements, member);
        if (value instanceof String) {
            return Collections.singletonList((String) value);
        }
        if (!(value instanceof List<?>)) {
            return Collections.emptyList();
        }
        List<?> list = (List<?>) value;
        List<String> names = new ArrayList<String>();
        for (Object item : list) {
            Object raw = item instanceof AnnotationValue ? ((AnnotationValue) item).getValue() : item;
            if (raw instanceof String) {
                names.add((String) raw);
            }
        }
        return names;
    }

    static Object annotationValue(AnnotationMirror mirror, Elements elements, String member) {
        for (Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry
                : elements.getElementValuesWithDefaults(mirror).entrySet()) {
            if (entry.getKey().getSimpleName().contentEquals(member)) {
                return entry.getValue().getValue();
            }
        }
        return null;
    }

    static final class AssembledProperty {

        private final String name;
        private final String typeSource;
        private final String initializer;
        private final boolean primitiveBoolean;
        private final boolean array;

        AssembledProperty(
                String name,
                String typeSource,
                String initializer,
                boolean primitiveBoolean,
                boolean array) {
            this.name = Objects.requireNonNull(name);
            this.typeSource = Objects.requireNonNull(typeSource);
            this.initializer = initializer;
            this.primitiveBoolean = primitiveBoolean;
            this.array = array;
        }

        static AssembledProperty fromType(String name, TypeMirror type, String initializer) {
            return new AssembledProperty(
                    name,
                    renderType(type),
                    initializer,
                    type.getKind() == TypeKind.BOOLEAN,
                    type.getKind() == TypeKind.ARRAY);
        }

        String name() {
            return name;
        }

        String typeSource() {
            return typeSource;
        }

        String initializer() {
            return initializer;
        }

        boolean primitiveBoolean() {
            return primitiveBoolean;
        }

        boolean array() {
            return array;
        }

        String getter() {
            String prefix = primitiveBoolean ? "is" : "get";
            return ParametersProcessor.accessor(prefix, name);
        }

        String setter() {
            return ParametersProcessor.accessor("set", name);
        }

        static String renderType(TypeMirror type) {
            switch (type.getKind()) {
                case BOOLEAN:
                    return "boolean";
                case BYTE:
                    return "byte";
                case SHORT:
                    return "short";
                case INT:
                    return "int";
                case LONG:
                    return "long";
                case CHAR:
                    return "char";
                case FLOAT:
                    return "float";
                case DOUBLE:
                    return "double";
                case ARRAY:
                    return renderType(((ArrayType) type).getComponentType()) + "[]";
                default:
                    return stripJavaLang(type.toString());
            }
        }

        private static String stripJavaLang(String typeName) {
            int generic = typeName.indexOf('<');
            String core = generic < 0 ? typeName : typeName.substring(0, generic);
            String suffix = generic < 0 ? "" : typeName.substring(generic);
            if (core.startsWith("java.lang.") && core.indexOf('.', "java.lang.".length()) < 0) {
                return core.substring("java.lang.".length()) + suffix;
            }
            return typeName;
        }
    }
}
