package com.pojo.parameters.processor;

import com.pojo.parameters.Parameters;

import javax.lang.model.SourceVersion;
import javax.lang.model.element.AnnotationMirror;
import javax.lang.model.element.AnnotationValue;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;
import javax.lang.model.type.ArrayType;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.Elements;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.function.BiConsumer;

/**
 * Collects annotation-declared properties and instance fields into one list.
 */
final class AssembledProperties {

    private final List<AssembledProperty> properties;

    AssembledProperties(List<AssembledProperty> properties) {
        this.properties = List.copyOf(properties);
    }

    List<AssembledProperty> properties() {
        return properties;
    }

    boolean isEmpty() {
        return properties.isEmpty();
    }

    static AssembledProperties from(
            TypeElement type,
            Parameters annotation,
            AnnotationMirror mirror,
            Elements elements,
            BiConsumer<Element, String> error) {
        Map<String, AssembledProperty> byName = new LinkedHashMap<>();

        if (!mergeExistingFields(type, byName, error)) {
            return null;
        }
        if (!addNamedStrings(type, annotation.String(), byName, error)) {
            return null;
        }
        if (!addPrimitiveShorthands(type, annotation, byName, error)) {
            return null;
        }
        if (!addOfProperties(type, mirror, elements, byName, error)) {
            return null;
        }
        if (byName.isEmpty()) {
            error.accept(type, "@Parameters must declare at least one property or instance field to merge.");
            return null;
        }
        return new AssembledProperties(new ArrayList<>(byName.values()));
    }

    String renderJava(String packageName, String className) {
        StringBuilder java = new StringBuilder();
        if (!packageName.isEmpty()) {
            java.append("package ").append(packageName).append(";\n\n");
        }
        java.append("import javax.annotation.processing.Generated;\n");
        if (properties.stream().anyMatch(AssembledProperty::array)) {
            java.append("import java.util.Arrays;\n");
        }
        java.append("import java.util.Objects;\n\n");
        java.append("/**\n");
        java.append(" * Generated by {@code @Parameters}. Do not edit.\n");
        java.append(" */\n");
        java.append("@Generated(\"com.pojo.parameters.processor.ParametersProcessor\")\n");
        java.append("public abstract class ").append(className).append(" {\n\n");
        for (AssembledProperty property : properties) {
            java.append("    private ").append(property.typeSource()).append(' ').append(property.name());
            if (property.initializer() != null) {
                java.append(" = ").append(property.initializer());
            }
            java.append(";\n");
        }
        java.append('\n');
        java.append("    protected ").append(className).append("() {\n");
        java.append("    }\n");
        for (AssembledProperty property : properties) {
            appendAccessors(java, property);
        }
        appendEqualsHashCodeToString(java, className);
        java.append("}\n");
        return java.toString();
    }

    private static boolean mergeExistingFields(
            TypeElement type,
            Map<String, AssembledProperty> byName,
            BiConsumer<Element, String> error) {
        for (Element enclosed : type.getEnclosedElements()) {
            if (enclosed.getKind() != ElementKind.FIELD || !(enclosed instanceof VariableElement field)) {
                continue;
            }
            if (field.getModifiers().contains(Modifier.STATIC)) {
                continue;
            }
            String name = field.getSimpleName().toString();
            if (!SourceVersion.isIdentifier(name) || SourceVersion.isKeyword(name)) {
                error.accept(field, "Cannot merge field into @Parameters: invalid name " + name);
                return false;
            }
            AssembledProperty property = AssembledProperty.fromType(name, field.asType(), null);
            if (!putMerged(type, byName, property, error)) {
                return false;
            }
        }
        return true;
    }

    private static boolean addOfProperties(
            TypeElement type,
            AnnotationMirror mirror,
            Elements elements,
            Map<String, AssembledProperty> byName,
            BiConsumer<Element, String> error) {
        if (mirror == null) {
            return true;
        }
        for (AnnotationMirror nested : nestedAnnotations(mirror, elements, "of")) {
            TypeMirror propertyType = classValue(nested, elements, "Class");
            if (propertyType == null) {
                error.accept(type, "Each @Of must declare Class.");
                return false;
            }
            List<String> names = stringValues(nested, elements, "names");
            if (names.isEmpty()) {
                String derived = decapitalize(simpleName(propertyType));
                if (!SourceVersion.isIdentifier(derived) || SourceVersion.isKeyword(derived)) {
                    error.accept(type, "Type " + propertyType
                            + " produces invalid field name '" + derived
                            + "'; declare names explicitly on @Of.");
                    return false;
                }
                names = List.of(derived);
            }
            for (String name : names) {
                if (!SourceVersion.isIdentifier(name) || SourceVersion.isKeyword(name)) {
                    error.accept(type, "Invalid @Of property name: " + name);
                    return false;
                }
                AssembledProperty property = AssembledProperty.fromType(name, propertyType, null);
                if (!putMerged(type, byName, property, error)) {
                    return false;
                }
            }
        }
        return true;
    }

    private static boolean addNamedStrings(
            TypeElement type,
            String[] names,
            Map<String, AssembledProperty> byName,
            BiConsumer<Element, String> error) {
        for (String name : names) {
            if (!SourceVersion.isIdentifier(name) || SourceVersion.isKeyword(name)) {
                error.accept(type, "Invalid String property name: " + name);
                return false;
            }
            AssembledProperty property = new AssembledProperty(name, "String", null, false, false);
            if (!putMerged(type, byName, property, error)) {
                return false;
            }
        }
        return true;
    }

    private static boolean addPrimitiveShorthands(
            TypeElement type,
            Parameters annotation,
            Map<String, AssembledProperty> byName,
            BiConsumer<Element, String> error) {
        for (boolean value : annotation.boolean_()) {
            String name = uniqueLiteralName("boolean", Boolean.toString(value), byName.keySet());
            AssembledProperty property = new AssembledProperty(name, "boolean", Boolean.toString(value), true, false);
            if (!putMerged(type, byName, property, error)) {
                return false;
            }
        }
        for (byte value : annotation.byte_()) {
            String name = uniqueLiteralName("byte", Byte.toString(value), byName.keySet());
            AssembledProperty property = new AssembledProperty(name, "byte", "(byte) " + value, false, false);
            if (!putMerged(type, byName, property, error)) {
                return false;
            }
        }
        for (short value : annotation.short_()) {
            String name = uniqueLiteralName("short", Short.toString(value), byName.keySet());
            AssembledProperty property = new AssembledProperty(name, "short", "(short) " + value, false, false);
            if (!putMerged(type, byName, property, error)) {
                return false;
            }
        }
        for (int value : annotation.int_()) {
            String name = uniqueLiteralName("int", Integer.toString(value), byName.keySet());
            AssembledProperty property = new AssembledProperty(name, "int", Integer.toString(value), false, false);
            if (!putMerged(type, byName, property, error)) {
                return false;
            }
        }
        for (long value : annotation.long_()) {
            String name = uniqueLiteralName("long", Long.toString(value), byName.keySet());
            AssembledProperty property = new AssembledProperty(name, "long", value + "L", false, false);
            if (!putMerged(type, byName, property, error)) {
                return false;
            }
        }
        for (char value : annotation.char_()) {
            String name = uniqueLiteralName("char", charName(value), byName.keySet());
            AssembledProperty property = new AssembledProperty(name, "char", charLiteral(value), false, false);
            if (!putMerged(type, byName, property, error)) {
                return false;
            }
        }
        for (float value : annotation.float_()) {
            String name = uniqueLiteralName("float", Float.toString(value), byName.keySet());
            AssembledProperty property = new AssembledProperty(name, "float", value + "f", false, false);
            if (!putMerged(type, byName, property, error)) {
                return false;
            }
        }
        for (double value : annotation.double_()) {
            String name = uniqueLiteralName("double", Double.toString(value), byName.keySet());
            AssembledProperty property = new AssembledProperty(name, "double", Double.toString(value), false, false);
            if (!putMerged(type, byName, property, error)) {
                return false;
            }
        }
        return true;
    }

    private static boolean putMerged(
            TypeElement type,
            Map<String, AssembledProperty> byName,
            AssembledProperty property,
            BiConsumer<Element, String> error) {
        AssembledProperty existing = byName.get(property.name());
        if (existing == null) {
            byName.put(property.name(), property);
            return true;
        }
        if (existing.typeSource().equals(property.typeSource())) {
            if (existing.initializer() == null && property.initializer() != null) {
                byName.put(property.name(), property);
            }
            return true;
        }
        error.accept(type, "Duplicate property name with conflicting types: " + property.name()
                + " (" + existing.typeSource() + " vs " + property.typeSource() + ")");
        return false;
    }

    private static void appendAccessors(StringBuilder java, AssembledProperty property) {
        java.append('\n');
        java.append("    public ").append(property.typeSource()).append(' ')
                .append(property.getter()).append("() {\n");
        java.append("        return this.").append(property.name()).append(";\n");
        java.append("    }\n\n");
        java.append("    public void ").append(property.setter()).append('(')
                .append(property.typeSource()).append(' ').append(property.name()).append(") {\n");
        java.append("        this.").append(property.name()).append(" = ").append(property.name()).append(";\n");
        java.append("    }\n");
    }

    private void appendEqualsHashCodeToString(StringBuilder java, String className) {
        java.append('\n');
        java.append("    @Override\n");
        java.append("    public boolean equals(Object o) {\n");
        java.append("        if (this == o) {\n");
        java.append("            return true;\n");
        java.append("        }\n");
        java.append("        if (!(o instanceof ").append(className).append(" that)) {\n");
        java.append("            return false;\n");
        java.append("        }\n");
        if (properties.isEmpty()) {
            java.append("        return true;\n");
        } else {
            java.append("        return ").append(equalsExpression()).append(";\n");
        }
        java.append("    }\n\n");
        java.append("    @Override\n");
        java.append("    public int hashCode() {\n");
        java.append("        return ").append(hashExpression()).append(";\n");
        java.append("    }\n\n");
        java.append("    @Override\n");
        java.append("    public String toString() {\n");
        java.append("        return \"").append(className).append("{\"\n");
        for (int i = 0; i < properties.size(); i++) {
            AssembledProperty property = properties.get(i);
            java.append("                + \"");
            if (i > 0) {
                java.append(", ");
            }
            java.append(property.name()).append("=\" + ");
            java.append(toStringFragment(property)).append('\n');
        }
        java.append("                + '}';\n");
        java.append("    }\n");
    }

    private String equalsExpression() {
        List<String> parts = new ArrayList<>();
        for (AssembledProperty property : properties) {
            String name = property.name();
            if (property.array()) {
                parts.add("Arrays.equals(this." + name + ", that." + name + ")");
            } else if ("float".equals(property.typeSource())) {
                parts.add("Float.compare(this." + name + ", that." + name + ") == 0");
            } else if ("double".equals(property.typeSource())) {
                parts.add("Double.compare(this." + name + ", that." + name + ") == 0");
            } else if (property.primitiveBoolean()
                    || Set.of("byte", "short", "int", "long", "char").contains(property.typeSource())) {
                parts.add("this." + name + " == that." + name);
            } else {
                parts.add("Objects.equals(this." + name + ", that." + name + ")");
            }
        }
        return String.join("\n                && ", parts);
    }

    private String hashExpression() {
        if (properties.isEmpty()) {
            return "0";
        }
        boolean anyArray = properties.stream().anyMatch(AssembledProperty::array);
        if (!anyArray) {
            StringBuilder args = new StringBuilder();
            for (int i = 0; i < properties.size(); i++) {
                if (i > 0) {
                    args.append(", ");
                }
                args.append("this.").append(properties.get(i).name());
            }
            return "Objects.hash(" + args + ")";
        }
        StringBuilder expr = new StringBuilder("1");
        for (AssembledProperty property : properties) {
            expr.append(" * 31 + ");
            if (property.array()) {
                expr.append("Arrays.hashCode(this.").append(property.name()).append(')');
            } else {
                expr.append("Objects.hashCode(this.").append(property.name()).append(')');
            }
        }
        return expr.toString();
    }

    private static String toStringFragment(AssembledProperty property) {
        if (property.array()) {
            return "Arrays.toString(this." + property.name() + ")";
        }
        return "this." + property.name();
    }

    static String uniqueLiteralName(String prefix, String rawValue, Set<String> used) {
        String sanitized = sanitize(rawValue);
        String base = prefix + '_' + sanitized;
        if (!SourceVersion.isIdentifier(base) || SourceVersion.isKeyword(base)) {
            base = prefix + "_v" + sanitized;
        }
        if (!SourceVersion.isIdentifier(base) || SourceVersion.isKeyword(base)) {
            base = prefix + "_v";
        }
        return uniqueName(base, used);
    }

    static String uniqueName(String base, Set<String> used) {
        if (!used.contains(base)) {
            return base;
        }
        int suffix = 2;
        String candidate;
        do {
            candidate = base + '_' + suffix;
            suffix++;
        } while (used.contains(candidate));
        return candidate;
    }

    static String sanitize(String raw) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < raw.length(); i++) {
            char c = raw.charAt(i);
            if (Character.isJavaIdentifierPart(c) && c != '$') {
                sb.append(c);
            } else if (c == '-') {
                sb.append('m');
            } else {
                sb.append('_');
            }
        }
        String sanitized = sb.toString().replaceAll("_+", "_");
        if (sanitized.startsWith("_")) {
            sanitized = sanitized.substring(1);
        }
        if (sanitized.endsWith("_")) {
            sanitized = sanitized.substring(0, sanitized.length() - 1);
        }
        return sanitized.isEmpty() ? "v" : sanitized;
    }

    static String decapitalize(String name) {
        if (name == null || name.isEmpty()) {
            return name;
        }
        if (name.length() > 1 && Character.isUpperCase(name.charAt(0)) && Character.isUpperCase(name.charAt(1))) {
            return name;
        }
        return Character.toLowerCase(name.charAt(0)) + name.substring(1);
    }

    static String simpleName(TypeMirror type) {
        String rendered = type.toString();
        int array = rendered.indexOf('[');
        String core = array < 0 ? rendered : rendered.substring(0, array);
        int lastDot = core.lastIndexOf('.');
        return lastDot < 0 ? core : core.substring(lastDot + 1);
    }

    static String charName(char value) {
        if (Character.isJavaIdentifierPart(value) && value != '$') {
            return Character.toString(value);
        }
        return Integer.toString((int) value);
    }

    static String charLiteral(char value) {
        return switch (value) {
            case '\'' -> "'\\''";
            case '\\' -> "'\\\\'";
            case '\n' -> "'\\n'";
            case '\r' -> "'\\r'";
            case '\t' -> "'\\t'";
            default -> (value >= 32 && value < 127)
                    ? "'" + value + "'"
                    : String.format("'\\u%04x'", (int) value);
        };
    }

    static List<AnnotationMirror> nestedAnnotations(AnnotationMirror mirror, Elements elements, String member) {
        Object value = annotationValue(mirror, elements, member);
        if (!(value instanceof List<?> list)) {
            return List.of();
        }
        List<AnnotationMirror> nested = new ArrayList<>();
        for (Object item : list) {
            Object raw = item instanceof AnnotationValue annotationValue ? annotationValue.getValue() : item;
            if (raw instanceof AnnotationMirror nestedMirror) {
                nested.add(nestedMirror);
            }
        }
        return nested;
    }

    static TypeMirror classValue(AnnotationMirror mirror, Elements elements, String member) {
        Object value = annotationValue(mirror, elements, member);
        return value instanceof TypeMirror typeMirror ? typeMirror : null;
    }

    static List<String> stringValues(AnnotationMirror mirror, Elements elements, String member) {
        Object value = annotationValue(mirror, elements, member);
        if (value instanceof String string) {
            return List.of(string);
        }
        if (!(value instanceof List<?> list)) {
            return List.of();
        }
        List<String> names = new ArrayList<>();
        for (Object item : list) {
            Object raw = item instanceof AnnotationValue annotationValue ? annotationValue.getValue() : item;
            if (raw instanceof String string) {
                names.add(string);
            }
        }
        return names;
    }

    static Object annotationValue(AnnotationMirror mirror, Elements elements, String member) {
        for (Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry
                : elements.getElementValuesWithDefaults(mirror).entrySet()) {
            if (entry.getKey().getSimpleName().contentEquals(member)) {
                return entry.getValue().getValue();
            }
        }
        return null;
    }

    record AssembledProperty(
            String name,
            String typeSource,
            String initializer,
            boolean primitiveBoolean,
            boolean array) {

        AssembledProperty {
            Objects.requireNonNull(name);
            Objects.requireNonNull(typeSource);
        }

        static AssembledProperty fromType(String name, TypeMirror type, String initializer) {
            return new AssembledProperty(
                    name,
                    renderType(type),
                    initializer,
                    type.getKind() == TypeKind.BOOLEAN,
                    type.getKind() == TypeKind.ARRAY);
        }

        String getter() {
            String prefix = primitiveBoolean ? "is" : "get";
            return ParametersProcessor.accessor(prefix, name);
        }

        String setter() {
            return ParametersProcessor.accessor("set", name);
        }

        static String renderType(TypeMirror type) {
            return switch (type.getKind()) {
                case BOOLEAN -> "boolean";
                case BYTE -> "byte";
                case SHORT -> "short";
                case INT -> "int";
                case LONG -> "long";
                case CHAR -> "char";
                case FLOAT -> "float";
                case DOUBLE -> "double";
                case ARRAY -> renderType(((ArrayType) type).getComponentType()) + "[]";
                default -> stripJavaLang(type.toString());
            };
        }

        private static String stripJavaLang(String typeName) {
            int generic = typeName.indexOf('<');
            String core = generic < 0 ? typeName : typeName.substring(0, generic);
            String suffix = generic < 0 ? "" : typeName.substring(generic);
            if (core.startsWith("java.lang.") && core.indexOf('.', "java.lang.".length()) < 0) {
                return core.substring("java.lang.".length()) + suffix;
            }
            return typeName;
        }
    }
}
